[default]
root = "."
libs = ['../../node_modules/', '../../']
tests = "./src/tests"
ffi = true
verbosity = 3
# Fork block mined at Apr-01-2022 12:00:21 AM UTC
fork_block_number = 14605885
remappings = [
    '@sense-finance/v1-utils=../utils',
    '@sense-finance/v1-core=../core',
    '@sense-finance/v1-fuse=./',
    '@rari-capital/solmate=../../node_modules/@rari-capital/solmate',
    '@openzeppelin/contracts=../../node_modules/@openzeppelin/contracts'
]