name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        token: ${{ secrets.ACCESS_TOKEN }}
    - uses: actions/setup-node@v2
      with:
        node-version: 14
        cache: yarn
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - uses: Swatinem/rust-cache@v1
      with:
          cache-on-failure: true

    - name: Install dependencies
      run: yarn install

    - name: Install Foundry
      uses: onbjerg/foundry-toolchain@v1
      with:
        version: nightly

    - name: Run linter
      run: yarn lint

    # When NOT in dev or master we run some basic scenarios (e.g 18 decimals and target decimals < and > than underlying decimals) 
    - name: Run local tests
      if: github.ref != 'refs/heads/dev' && github.ref != 'refs/heads/master'
      run: yarn test

    - name: Run mainnet tests
      run: yarn test:mainnet

    # Only when there's a push to dev or master, we run all the possible combinations of tests (PAUSED UNTIL FIXED)
    - name: Run local tests with all possible combinations of ERC20, nonERC20, ERC4626 and 6, 8 and 18 decimals for Target, Underlying and Stake
      if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/master'
      run: yarn workspace @sense-finance/v1-core run test:fuzz

    - name: Check deploy scripts on a local mainnet fork
      run: cd pkg/deployments; yarn deploy:hardhat-fork:prod
      env:
        ALCHEMY_KEY: ${{ secrets.ALCHEMY_KEY }}
        MNEMONIC: ${{ secrets.MNEMONIC }}
        FORK_TOP_UP: ${{ secrets.FORK_TOP_UP }}

    - name: Check simulated testchain env scripts on a local mainnet fork
      run: cd pkg/deployments; yarn deploy:hardhat-fork:sim
      env:
        ALCHEMY_KEY: ${{ secrets.ALCHEMY_KEY }}
        MNEMONIC: ${{ secrets.MNEMONIC }}
        FORK_TOP_UP: ${{ secrets.FORK_TOP_UP }}

    - name: Generate gas snapshot
      run: yarn gas-snapshot
      env:
        ALCHEMY_KEY: ${{ secrets.ALCHEMY_KEY }}
        MNEMONIC: ${{ secrets.MNEMONIC }}

    - name: Commit changes
      if: ${{ github.ref == 'refs/heads/dev' }}
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: '[ci] gas snapshot'
        branch: ${{ github.head_ref }}
        file_pattern: gas-snapshots/*
